/**
*Generated by StarUML(tm) Java Add-In
*  @ Project : basis
*  @ File Name : MenuServiceImpl.java
*  @ Date : 2012/9/21
*  @ Author : wxliu
*/



package com.crowdfunding.core.service.impl;

import java.util.List;

import org.apache.log4j.Logger;

import com.crowdfunding.core.condition.MenuCondition;
import com.crowdfunding.core.dao.IBaseDao;
import com.crowdfunding.core.domain.Menu;


public class MenuServiceImpl implements com.crowdfunding.core.service.IMenuService {
	private static final Logger logger =Logger.getLogger(MenuServiceImpl.class);
	private IBaseDao dao;
	
	public void setDao(IBaseDao dao) {
		this.dao = dao;
	}

	public Menu queryMenuById(String id) {
		return dao.getObject(Menu.class, id);
	}

	public List<Menu> queryMenuList(MenuCondition condition) {
		return dao.queryObjectList(condition);
	}
}
